language: php

php:
    - '7.1'
    - '7.2'
    - nightly

ignore:
    - README.md
    - .gitignore

matrix:
    fast_finish: true
    include:
        - php: '7.1'
        - php: '7.2'
    allow_failures:
        -   php: nightly

before_script: composer install

script: phpunit