language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - nightly

env:
    PHPUNIT_VERSION="8.*"

ignore:
    - README.md
    - .gitignore

matrix:
    fast_finish: true
    allow_failures:
        - php:
            - '7.2'
            - nightly

before_script: composer install

script: php bin/phpunit