language: php

matrix:
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.2
    allow_failures:
        - php: nightly
ignore:
    - README.md
    - .gitignore

before_script: composer install

script: phpunit