parameters:
    sc_mapper.compiler_cache_dir: '%kernel.cache_dir%/seacommerce/mapper/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Seacommerce\MapperBundle\DefaultMapperFactory:
        arguments:
            $registrations: !tagged mapper.mapping_registration

    Seacommerce\Mapper\MapperInterface:
        factory: ['@Seacommerce\MapperBundle\DefaultMapperFactory', create]
        public: trie

    Seacommerce\Mapper\Compiler\PropertyAccessCompiler:
        arguments:
            $cacheFolder: '%sc_mapper.compiler_cache_dir%'

    Seacommerce\Mapper\Compiler\CompilerInterface:
        alias: Seacommerce\Mapper\Compiler\PropertyAccessCompiler
        public: true

    Seacommerce\MapperBundle\CacheWarmer:
        public: true

    Seacommerce\MapperBundle\Doctrine\DoctrineMappingRegistration: ~