parameters: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Seacommerce\MapperBundle\RegistryFactory:
        arguments:
            $scope: 'default'
            $registrations: !tagged mapper.mapping_registration

    Seacommerce\Mapper\Registry:
        factory: ['@Seacommerce\MapperBundle\RegistryFactory', getRegistry]

    Seacommerce\Mapper\RegistryInterface:
        alias: Seacommerce\Mapper\Registry
        public: true

    Seacommerce\Mapper\Mapper: ~

    Seacommerce\Mapper\MapperInterface:
        alias: Seacommerce\Mapper\Mapper
        public: true

    Seacommerce\Mapper\Compiler\PropertyAccessCompiler: ~

    Seacommerce\Mapper\Compiler\CompilerInterface:
        alias: Seacommerce\Mapper\Compiler\PropertyAccessCompiler
        public: true